### ISSUE TITLE
MVP Review: User authentication

### ISSUE THREAD

**Issue by RosemaryGonzaga** [andrew-elmore/couchcorn#3]
Hey Andrew, nice work with user auth so far! There are some things to address listed below.

Most of these can wait until after Friday, but here are a few items that should be addressed before Friday:

# High priority items to address before Friday:
- [x] Splash page: you need to render something at the root route (instead of being redirected to the "/login" page)
    - Add a background image for the splash page and login forms
- [x] Login form inputs need labels 
    - For both the login and signup forms, the format should actually be placeholder text inside the input, rather than label tags
- [x] Add a working demo login button

Let me know if you have any questions!

----

# Full User Auth Checklist

## Functionality

- [ ] The main button with logo should link to `/`
- [ ] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
    - If I trigger errors on the login page, I can still see them when I switch to the signup page, and vice versa. To clear errors between auth forms, look into dispatching a `CLEAR_ERRORS` action when each form component unmounts (use the `componentWillUnmount` lifecycle method)
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [ ] Pressing enter after filling out the session form should use the form data, not the demo user --> n/a until you implement a demo login

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
    - Styling quick fixes:
        - [ ] Add padding to inputs (a small thing, but goes a long way to making site look more polished)
        - [ ] Add an image background to the splash page (see comment below) and the login page
        - [ ] Add a logo where appropriate
        - [ ] Fonts: Netflix seems to use the same sans-serif font throughout its site. Choose a sans-serif font that seems similar to the one Netflix uses and add it to your css reset file.
        - [ ] Add a border-radius to the login inputs
- [ ] All relevant elements should have `cursor: pointer` on hover
    - Add this to your forms' submit buttons ("Log In!" and "CONTINUE")
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)

## Misc: 
- [ ] Remove dead links / dead content: 
    - "Login with Facebook"
    - The "Learn more" link at the end of your captcha message (but you can keep the main message - I like the tongue-in-cheek twist on it)
    - The "Need help?" link below the login button in the login form

**Comment by andrew-elmore** [comment]
Done
